#defaults:
hydra:
  run:
    # Output directory for normal runs
    dir: ./
test_frequency: 1 # unused?
a: 2
labelled_per_class: 100
missing_batch_size: 128
labelled_batch_size: 128
n_steps: 500
use_wandb: true
max_epochs: 50
optimizer_config:
  lr: 4e-3
defaults:
  - model_config: vae

